### ISSUE TITLE
实在想不明白，启动mongo服务为什么要用 docker

### ISSUE THREAD

**Issue by nearxu** [page-pipepline/pipeline-mongo#1]
而且既然用了egg，直接用egg 启动mongo 就好了吗，麻烦能简单点，直接express 启动mongo服务。

**Comment by CntChen** [comment]
egg 应该只是连接现有的 mongo 服务, 比如用 [egg-mongoose](https://github.com/eggjs/egg-mongoose).
用 docker 本地第一次使用比较麻烦, 后续使用会方便一点.
我后续提供一个单独的 mongo 脚本, 已有 mongodb 环境就可以直接用.

**Comment by nearxu** [comment]
非常感谢你回复，我想问一下，我现在用docker ps ，显示我的数据是空，我平时启动mongod --dbpath ,
我尝试 mongo -u user -p pass .. ,报错说我的地址不合法。

**Comment by CntChen** [comment]
我对mongo也不是很熟, 可以用 robo 3t 可视化工具看下: https://robomongo.org/.
